include:
  - local: /.gitlab/security-ci.yml
  - local: /.gitlab/secret-ci.yml
  - local: /.gitlab/linter-ci.yml
  - local: /.gitlab/type-checker-ci.yml
  - local: /.gitlab/unit-tests-ci.yml
  - local: /.gitlab/tag-ci.yml
  - local: /.gitlab/publish-ci.yml
stages:
  - test
  - release
  - publish
security:
  extends: .security
secret:
  extends: .secret
linter:
  extends: .linter
type_checker:
  extends: .type_checker
unit_tests:
  extends: .unit_tests
.tag_base:
  extends: .tag
  needs:
    - security
    - secret
    - linter
    - type_checker
    - unit_tests
tag:major:
  extends: .tag_base
tag:minor:
  extends: .tag_base
tag:patch:
  extends: .tag_base
publish:
  extends: .publish
